apiVersion: v1
data:
  mapRoles: |
    - rolearn: arn:aws:iam::851974187100:role/eksctl-roboshop-nodegroup-spot-NodeInstanceRole-6U7g7Hpmyayu
      groups:
      - system:bootstrappers
      - system:nodes
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    - groups:
      - roboshop-trainee
      userarn: arn:aws:iam::851974187100:user/suresh
      username: suresh
    - groups:
      - roboshop-admin
      userarn: arn:aws:iam::851974187100:user/ramesh
      username: ramesh
    - groups:
      - roboshop-admins
      userarn: arn:aws:iam::851974187100:user/hareesh
      username: ramesh
kind: ConfigMap
metadata:
  creationTimestamp: "2026-04-15T05:24:42Z"
  name: aws-auth
  namespace: kube-system
  uid: 7bcc9c7e-7c39-4d9f-b0eb-b449a0f2a8f5
