apiVersion: rbac.authorization.k8s.io/v1

kind: RoleBinding
metadata:
  name: roboshop-admins
  namespace: roboshop
subjects:
- kind: User
  name: hareesh 
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role #this must be Role or ClusterRole
  name: roboshop-admins # this must match the name of the Role or ClusterRole you wish to bind to
  apiGroup: rbac.authorization.k8s.io
